### ISSUE TITLE
kube-scheduler config file api version

### ISSUE THREAD

**Issue by cgcgbcbc** [kelseyhightower/kubernetes-the-hard-way#427]
the api version `componentconfig/v1alpha1` has been deprecated since 1.9 is not supported in 1.13, which should be changed to `apiVersion: kubescheduler.config.k8s.io/v1alpha1`

**Comment by jasperroel** [comment]
Just here to correctly indent the fix:

```
cat <<EOF | sudo tee /etc/kubernetes/config/kube-scheduler.yaml
apiVersion: kubescheduler.config.k8s.io/v1alpha1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"
leaderElection:
  leaderElect: true
EOF
```

Then verify with
`systemctl status kube-scheduler`
and see that the status has moved to `Active: active (running)` (it auto-restarts every 5 seconds).
Make sure to do this on all (3) controllers.

Run
`kubectl get componentstatuses --kubeconfig admin.kubeconfig`
to verify that the `scheduler` is reporting **Healthy** as well.

**Comment by ioanc** [comment]
> as per [https://github.com/kubernetes/kubernetes/pull/66916](url) , using a config file is still alpha.
> changed the service file to use the same options as in the config file

[Unit]
Description=Kubernetes Scheduler
Documentation=https://github.com/kubernetes/kubernetes

[Service]
ExecStart=/usr/local/bin/kube-scheduler \
  --leader-elect=true \
  --kubeconfig=/var/lib/kubernetes/kube-scheduler.kubeconfig \
  --v=2
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target

**Comment by kelseyhightower** [comment]
Fixed on master.

**Comment by JulienBreux** [comment]
For the future readers, the new version is currently: `kubescheduler.config.k8s.io/v1beta1`

Example:
```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"
leaderElection:
  leaderElect: true
```

/ref https://kubernetes.io/docs/reference/scheduling/config/

**Comment by moluzhui** [comment]
> For the future readers, the new version is currently: `kubescheduler.config.k8s.io/v1beta1`
> 
> Example:
> 
> ```yaml
> apiVersion: kubescheduler.config.k8s.io/v1beta1
> kind: KubeSchedulerConfiguration
> clientConnection:
>   kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"
> leaderElection:
>   leaderElect: true
> ```
> 
> /ref https://kubernetes.io/docs/reference/scheduling/config/

Whether KubeSchedulerConfiguration only enable it in 1.19, I found some information on v1.18 already started to use this, but I through the `kubectl api-resources` did not find this kind of resources

**Comment by amit4aws** [comment]
@JulienBreux I am still seeing the same Issue. My yaml for kube-scheduler looks like this

apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"
leaderElection:
  leaderElect: true
  
  After reloading and restarting I am still not able to restart the scheduler
  
  ● kube-scheduler.service - Kubernetes Scheduler
   Loaded: loaded (/etc/systemd/system/kube-scheduler.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2022-01-20 11:42:38 UTC; 1s ago
     Docs: https://github.com/kubernetes/kubernetes
  Process: 9675 ExecStart=/usr/local/bin/kube-scheduler --config=/etc/kubernetes/config/kube-scheduler.yaml --v=2 (code=exited, status=255)
 Main PID: 9675 (code=exited, status=255)

 kube-scheduler[9675]: I0120 11:42:38.664840    9675 flags.go:27] FLAG: --scheduler-name="default-scheduler"
 kube-scheduler[9675]: I0120 11:42:38.664847    9675 flags.go:27] FLAG: --stderrthreshold="2"
 kube-scheduler[9675]: I0120 11:42:38.664853    9675 flags.go:27] FLAG: --use-legacy-policy-config="false"
 kube-scheduler[9675]: I0120 11:42:38.664860    9675 flags.go:27] FLAG: --v="2"
 kube-scheduler[9675]: I0120 11:42:38.664866    9675 flags.go:27] FLAG: --version="false"
 kube-scheduler[9675]: I0120 11:42:38.664878    9675 flags.go:27] FLAG: --vmodule=""
 kube-scheduler[9675]: F0120 11:42:38.665137    9675 helpers.go:119] error: no kind "KubeSchedulerConfiguration" is registered for version "kubescheduler.config.k8s.io/v1beta1"
 systemd[1]: kube-scheduler.service: Main process exited, code=exited, status=255/n/a
 systemd[1]: kube-scheduler.service: Unit entered failed state.
 systemd[1]: kube-scheduler.service: Failed with result 'exit-code'.

My Kuber version is

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jamesilse** [comment]
Ran into this same error today.
The apiVersion is now v1beta2
Example:
`apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"
leaderElection:
  leaderElect: true`

**Comment by wintersolutions** [comment]
For v1.25:

```
apiVersion: kubescheduler.config.k8s.io/v1
```
or
```
apiVersion: kubescheduler.config.k8s.io/v1beta3
```

https://kubernetes.io/docs/reference/scheduling/config/

**Comment by mengwanguc** [comment]
> For v1.25:
> 
> ```
> apiVersion: kubescheduler.config.k8s.io/v1
> ```
> 
> or
> 
> ```
> apiVersion: kubescheduler.config.k8s.io/v1beta3
> ```
> 
> https://kubernetes.io/docs/reference/scheduling/config/

Thank you bro you saved my day!
