### ISSUE TITLE
cfssl and cfssljson links broken

### ISSUE THREAD

**Issue by shervinkh** [kelseyhightower/kubernetes-the-hard-way#739]
`storage.googleapis.com` links to `cfssl` and `cfssljson` are broken in https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/02-client-tools.md. They'll return 403 Forbidden.

**Comment by ioanc** [comment]
check my pull request [#740](https://github.com/kelseyhightower/kubernetes-the-hard-way/pull/740)
I should fix the download problem

**Comment by aws-apradana** [comment]
happens to me too

**Comment by ioanc** [comment]
Check the pull request https://github.com/kelseyhightower/kubernetes-the-hard-way/pull/741
It should solve your issue @aws-apradana

**Comment by aws-apradana** [comment]
Thanks @ioanc , I already pulled from the new link

**Comment by daryltamo** [comment]
still having the same problem. curling the link would return 403 Forbidden
